import 'package:flutter/material.dart';
import 'package:parentledger/l10n/context_l10n.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:printing/printing.dart';
import 'package:parentledger/services/legal_case_report_pdf_service.dart';

import 'package:parentledger/design/design.dart';
import 'package:parentledger/models/legal_export_models.dart';
import 'package:parentledger/ui/widgets/court_document_send_sheet.dart';

class LegalExportPreviewScreen extends StatefulWidget {
  final ExportDocument document;

  /// Counsel / non-Pro preview: prominent watermark (not a substitute for full export).
  final bool watermarked;

  const LegalExportPreviewScreen({
    super.key,
    required this.document,
    this.watermarked = false,
  });

  @override
  State<LegalExportPreviewScreen> createState() =>
      _LegalExportPreviewScreenState();
}

class _LegalExportPreviewScreenState extends State<LegalExportPreviewScreen> {
  final DateFormat _date = DateFormat("MMMM d, yyyy • HH:mm");

  String formatHeader(String raw) {
    try {
      final parts = raw.split("-");
      final dt = DateTime(
        int.parse(parts[0]),
        int.parse(parts[1]),
        int.parse(parts[2]),
      );
      return DateFormat("MMMM d, yyyy").format(dt);
    } catch (_) {
      return raw;
    }
  }

  /// Full export text — same payload emailed to counsel / court.
  String buildPlainTextDocument() {
    final buffer = StringBuffer();

    buffer.writeln(widget.document.title);
    buffer.writeln("Case ID: ${widget.document.caseId}");
    buffer.writeln(
      "Generated: ${_date.format(widget.document.generatedAt)}",
    );
    buffer.writeln("");

    for (final section in widget.document.sections) {
      buffer.writeln(section.header);

      for (final e in section.entries) {
        buffer.writeln(
          "${_date.format(e.timestamp)} - ${e.title}: ${e.description}",
        );

        if (e.metadata != null) {
          buffer.writeln("(${e.metadata})");
        }
      }

      buffer.writeln("");
    }

    buffer.writeln('---');
    buffer.writeln('Generated by ParentLedger');
    buffer.writeln(
      'This document is a compiled record of logged events and is intended '
      'for documentation purposes only.',
    );

    return buffer.toString();
  }

  Future<void> copyDocument() async {
    await Clipboard.setData(
      ClipboardData(text: buildPlainTextDocument()),
    );

    if (!mounted) return;

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(context.tTone('copiedToClipboard')),
        backgroundColor: PLDesign.surface,
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  Future<void> _openSendSheet(CourtRecipientRole role) async {
    final ok = await showCourtDocumentSendSheet(
      context,
      document: widget.document,
      plainTextBody: buildPlainTextDocument(),
      initialRole: role,
    );

    if (ok != true || !mounted) return;

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: const Text(
          'Court document sent — delivery confirmed from ParentLedger.',
        ),
        backgroundColor: PLDesign.success,
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  Future<void> exportPDF() async {
    final caseId = widget.document.caseId;
    final bytes = await LegalCaseReportPdfService.buildPdfBytes(caseId);
    if (!context.mounted) return;
    await Printing.layoutPdf(
      onLayout: (format) async => bytes,
    );
  }

  Widget buildEntry(ExportEntry e) {
    return Container(
      margin: const EdgeInsets.only(bottom: 14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            _date.format(e.timestamp),
            style: const TextStyle(
              fontSize: 12,
              color: PLDesign.textMuted,
            ),
          ),
          const SizedBox(height: 2),
          Text(
            e.title,
            style: const TextStyle(
              fontWeight: FontWeight.w600,
              color: PLDesign.textPrimary,
            ),
          ),
          Text(
            e.description,
            style: PLDesign.legalBody.copyWith(fontSize: 14),
          ),
          if (e.metadata != null)
            Text(
              e.metadata!,
              style: const TextStyle(
                fontSize: 12,
                color: PLDesign.info,
              ),
            ),
        ],
      ),
    );
  }

  Widget buildSection(ExportSection section) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          formatHeader(section.header),
          style: const TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.bold,
            color: PLDesign.textPrimary,
          ),
        ),
        const SizedBox(height: 10),
        ...section.entries.map(buildEntry),
        const SizedBox(height: 22),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    final doc = widget.document;

    return Scaffold(
      backgroundColor: PLDesign.background,
      extendBodyBehindAppBar: false,
      appBar: AppBar(
        elevation: 0,
        backgroundColor: PLDesign.surface,
        foregroundColor: PLDesign.textPrimary,
        title: Text(
          doc.title,
          style: const TextStyle(
            fontSize: 17,
            fontWeight: FontWeight.w600,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.copy_rounded),
            tooltip: 'Copy',
            onPressed: copyDocument,
          ),
          IconButton(
            icon: const Icon(Icons.picture_as_pdf_outlined),
            tooltip: 'PDF',
            onPressed: exportPDF,
          ),
        ],
      ),
      body: Container(
        width: double.infinity,
        decoration: PLDesign.screenGradient,
        child: Column(
          children: [
            Expanded(
              child: Center(
                child: ConstrainedBox(
                  constraints: const BoxConstraints(maxWidth: 720),
                  child: Container(
                    margin: const EdgeInsets.fromLTRB(16, 16, 16, 8),
                    padding: const EdgeInsets.all(22),
                    decoration: PLDesign.legalCard,
                    child: Stack(
                      children: [
                        ListView(
                          shrinkWrap: true,
                          children: [
                            Text(
                              doc.title,
                              style: const TextStyle(
                                fontSize: 22,
                                fontWeight: FontWeight.bold,
                                color: PLDesign.textPrimary,
                              ),
                            ),
                            const SizedBox(height: 8),
                            Text(
                              'Case ID: ${doc.caseId}',
                              style: PLDesign.body,
                            ),
                            Text(
                              'Generated: ${_date.format(doc.generatedAt)}',
                              style: PLDesign.body,
                            ),
                            const Divider(height: 28, color: PLDesign.border),
                            ...doc.sections.map(buildSection),
                            const Divider(color: PLDesign.border),
                            const SizedBox(height: 8),
                            Text(
                              'Generated by ParentLedger',
                              style: PLDesign.caption,
                            ),
                            const SizedBox(height: 6),
                            Text(
                              'This document is a compiled record of logged events '
                              'and is intended for documentation purposes only.',
                              style: PLDesign.caption.copyWith(fontSize: 11),
                            ),
                          ],
                        ),
                        if (widget.watermarked)
                          Positioned.fill(
                            child: IgnorePointer(
                              child: Center(
                                child: Transform.rotate(
                                  angle: -0.45,
                                  child: Text(
                                    'COUNSEL COPY — WATERMARKED',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 26,
                                      fontWeight: FontWeight.w900,
                                      color:
                                          PLDesign.danger.withValues(alpha: 0.18),
                                      letterSpacing: 1.1,
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
            Material(
              color: PLDesign.surface,
              elevation: 12,
              child: SafeArea(
                top: false,
                child: Padding(
                  padding: const EdgeInsets.fromLTRB(16, 12, 16, 16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Text(
                        'Deliver to counsel or court',
                        textAlign: TextAlign.center,
                        style: PLDesign.caption.copyWith(
                          letterSpacing: 0.4,
                          color: PLDesign.textMuted,
                        ),
                      ),
                      const SizedBox(height: 12),
                      Row(
                        children: [
                          Expanded(
                            child: _SendPillButton(
                              icon: Icons.balance_rounded,
                              label: 'Attorney',
                              onTap: () {
                                HapticFeedback.selectionClick();
                                _openSendSheet(CourtRecipientRole.attorney);
                              },
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: _SendPillButton(
                              icon: Icons.account_balance_rounded,
                              label: 'Judge',
                              onTap: () {
                                HapticFeedback.selectionClick();
                                _openSendSheet(CourtRecipientRole.judge);
                              },
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _SendPillButton extends StatelessWidget {
  const _SendPillButton({
    required this.icon,
    required this.label,
    required this.onTap,
  });

  final IconData icon;
  final String label;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return DecoratedBox(
      decoration: BoxDecoration(
        gradient: PLDesign.primaryGradient,
        borderRadius: BorderRadius.circular(14),
        boxShadow: PLDesign.softShadow,
      ),
      child: Material(
        color: Colors.transparent,
        child: InkWell(
          onTap: onTap,
          borderRadius: BorderRadius.circular(14),
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 12),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(icon, color: Colors.white, size: 22),
                const SizedBox(width: 8),
                Text(
                  label,
                  style: PLDesign.buttonText.copyWith(fontSize: 15),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
