// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzlG0CDHMzepP1prLQnH8hXGwbG4PhdI',
    appId: '1:884928621500:android:a77997b61cc170095899b9',
    messagingSenderId: '884928621500',
    projectId: 'parentledger-prod',
    databaseURL: 'https://parentledger-prod-default-rtdb.firebaseio.com',
    storageBucket: 'parentledger-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESmwjdXKylNG2ky7xvVjnE1HftHJjAkY',
    appId: '1:884928621500:ios:9b02aca989a6d76b5899b9',
    messagingSenderId: '884928621500',
    projectId: 'parentledger-prod',
    databaseURL: 'https://parentledger-prod-default-rtdb.firebaseio.com',
    storageBucket: 'parentledger-prod.firebasestorage.app',
    iosBundleId: 'com.parentledger.app',
  );

  /// Desktop Windows uses the same Firebase project as Android until a dedicated
  /// Windows app is registered in the Firebase Console (run `flutterfire configure`).
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIzlG0CDHMzepP1prLQnH8hXGwbG4PhdI',
    appId: '1:884928621500:android:a77997b61cc170095899b9',
    messagingSenderId: '884928621500',
    projectId: 'parentledger-prod',
    databaseURL: 'https://parentledger-prod-default-rtdb.firebaseio.com',
    storageBucket: 'parentledger-prod.firebasestorage.app',
  );

}