// Generates triple-tone ARB files and lib/l10n/tone_string_resolver.g.dart
// from the pre-tone flat app_en.arb / app_es.arb (run once after editing flat ARBs).
//
// Usage: dart run tool/generate_tone_l10n.dart
//
// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

/// English copy overrides: base key -> tone -> string (omit tone to fall back to flat value).
const Map<String, Map<String, String>> kEnToneOverrides = {
  'addExpense': {
    '_neutral': '+ Add Expense',
    '_professional': 'Record expense',
    '_legal': 'Document expense',
  },
  'addFirstExpense': {
    '_professional': 'Add first expense record',
    '_legal': 'Create initial expense entry',
  },
  'missedOverdueExchanges': {
    '_neutral': 'Missed or overdue exchanges',
    '_professional': 'Exchanges not completed on schedule',
    '_legal': 'Scheduled exchanges not completed as documented',
  },
  'noMissedOrOverdueExchanges': {
    '_neutral': 'No missed or overdue exchanges detected in this case record.',
    '_professional': 'No incomplete scheduled exchanges in the current record.',
    '_legal': 'No documented failures to complete scheduled exchanges in this matter.',
  },
  'messages': {
    '_professional': 'Case messages',
    '_legal': 'Communication log (case file)',
  },
  'flaggedMessagesRecord': {
    '_professional': 'Flagged messages (review set)',
    '_legal': 'Flagged communications (record subset)',
  },
  'courtRecordStatusTitle': {
    '_professional': 'Record status',
    '_legal': 'Matter record status',
  },
  'caseOverviewEyebrow': {
    '_neutral': 'CASE OVERVIEW',
    '_professional': 'Case overview',
    '_legal': 'MATTER OVERVIEW',
  },
  'insightsTitle': {
    '_professional': 'Case insights',
    '_legal': 'Analytical overview',
  },
  'courtCommunicationSummary': {
    '_professional': 'Communication summary',
    '_legal': 'Chronological communication summary',
  },
};

void main() {
  final root = Directory.current;
  _expandArb(
    root,
    path: 'lib/l10n/app_en.arb',
    locale: 'en',
    overrides: kEnToneOverrides,
  );
  _expandArb(
    root,
    path: 'lib/l10n/app_es.arb',
    locale: 'es',
    overrides: const {}, // Spanish: triple from existing Spanish neutral text
  );
  _writeResolver(root, enPath: 'lib/l10n/app_en.arb');
  stdout.writeln('Done. Run: flutter gen-l10n');
}

void _expandArb(
  Directory root, {
  required String path,
  required String locale,
  required Map<String, Map<String, String>> overrides,
}) {
  final file = File('${root.path}/$path');
  final raw = json.decode(file.readAsStringSync()) as Map<String, dynamic>;
  final alreadyExpanded = raw.keys.any(
    (k) =>
        k is String &&
        !k.startsWith('@') &&
        k.endsWith('_neutral'),
  );
  if (alreadyExpanded) {
    stdout.writeln('Skip expand (already tone keys): $path');
    return;
  }

  final out = <String, dynamic>{'@@locale': locale};

  final keys = <String>[];
  for (final e in raw.entries) {
    if (e.key == '@@locale') continue;
    if (e.key.startsWith('@')) continue;
    keys.add(e.key);
  }

  for (final k in keys) {
    final v = raw[k];
    final meta = raw['@$k'];
    if (v is! String) continue;

    final o = overrides[k];
    final neutral = o?['_neutral'] ?? v;
    final professional = o?['_professional'] ?? neutral;
    final legal = o?['_legal'] ?? professional;

    for (final suffix in ['_neutral', '_professional', '_legal']) {
      final text = suffix == '_neutral'
          ? neutral
          : suffix == '_professional'
              ? professional
              : legal;
      final nk = '$k$suffix';
      out[nk] = text;
      if (meta is Map<String, dynamic>) {
        out['@$nk'] = json.decode(json.encode(meta)) as Map<String, dynamic>;
      }
    }
  }

  const encoder = JsonEncoder.withIndent('  ');
  file.writeAsStringSync('${encoder.convert(out)}\n');
}

void _writeResolver(Directory root, {required String enPath}) {
  final file = File('${root.path}/$enPath');
  final raw = json.decode(file.readAsStringSync()) as Map<String, dynamic>;
  final bases = <String>[];
  for (final e in raw.entries) {
    if (e.key == '@@locale' || e.key.startsWith('@')) continue;
    if (e.value is! String) continue;
    if (!e.key.endsWith('_neutral')) continue;
    bases.add(e.key.substring(0, e.key.length - '_neutral'.length));
  }
  bases.sort();

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/generate_tone_l10n.dart — do not edit by hand.')
    ..writeln()
    ..writeln("import 'app_localizations.dart';")
    ..writeln("import 'tone_models.dart';")
    ..writeln()
    ..writeln('String toneString(AppLocalizations loc, String key, UiTone tone) {')
    ..writeln('  switch (key) {');

  for (final k in bases) {
    final metaKey = '@${k}_neutral';
    final meta = raw[metaKey];
    if (meta is Map && meta['placeholders'] != null) {
      continue; // use toneWelcome / toneBalanceMinutes / future helpers
    }
    final id = k.replaceAll(r'$', r'$').replaceAll('-', '_');
    if (id != k || k.contains(r'$')) {
      throw UnsupportedError('Resolver key not supported: $k');
    }
    final n = _getter(k, '_neutral');
    final p = _getter(k, '_professional');
    final l = _getter(k, '_legal');
    buf.writeln("    case '$k':");
    buf.writeln('      switch (tone) {');
    buf.writeln('        case UiTone.neutral:');
    buf.writeln('          return loc.$n;');
    buf.writeln('        case UiTone.professional:');
    buf.writeln('          return loc.$p;');
    buf.writeln('        case UiTone.legal:');
    buf.writeln('          return loc.$l;');
    buf.writeln('      }');
  }

  buf
    ..writeln('    default:')
    ..writeln("      return key; // unknown key — surface for debugging")
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln('String toneWelcome(AppLocalizations loc, String name, UiTone tone) {')
    ..writeln('  switch (tone) {')
    ..writeln('    case UiTone.neutral:')
    ..writeln('      return loc.welcome_neutral(name);')
    ..writeln('    case UiTone.professional:')
    ..writeln('      return loc.welcome_professional(name);')
    ..writeln('    case UiTone.legal:')
    ..writeln('      return loc.welcome_legal(name);')
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln(
        'String toneBalanceMinutes(AppLocalizations loc, int minutes, UiTone tone) {')
    ..writeln('  switch (tone) {')
    ..writeln('    case UiTone.neutral:')
    ..writeln('      return loc.balanceUpdatedMinutesAgo_neutral(minutes);')
    ..writeln('    case UiTone.professional:')
    ..writeln('      return loc.balanceUpdatedMinutesAgo_professional(minutes);')
    ..writeln('    case UiTone.legal:')
    ..writeln('      return loc.balanceUpdatedMinutesAgo_legal(minutes);')
    ..writeln('  }')
    ..writeln('}');

  File('${root.path}/lib/l10n/tone_string_resolver.g.dart')
      .writeAsStringSync(buf.toString());
}

String _getter(String base, String suffix) {
  final full = '$base$suffix';
  // ARB keys like "continueLabel" map to getters continueLabel_neutral
  return full.replaceAll('-', '_');
}
